[WIP]Podman
openSUSE/openSUSE-docs-revamped pull request #100
Opened 2021-03-22 07:59 UTC by apinter

2021-03-31 10:56 UTC, why-not-try-calmer approved these changes

2021-03-31 10:56 UTC, why-not-try-calmer commented
Yeah when I asked if we had reviewers I meant reviewers able to make comments in this very convo... Do we have that?

2021-03-31 14:14 UTC, apinter commented
> Yeah when I asked if we had reviewers I meant reviewers able to make comments in this very convo... Do we have that?

WIP

2021-04-09 08:36 UTC, thunderbirdtr requested changes
Suggestion for docs and typo checks

2021-04-09 08:36 UTC, thunderbirdtr commented on project/docs/install_podman.md
> +* https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md
https://podman.io/
http://docs.podman.io/en/latest/
http://docs.podman.io/en/latest/Tutorials.html

Main podman-doc  and  "tutorials" links would be nice to add it.

2021-04-09 08:36 UTC, thunderbirdtr commented on project/docs/install_podman.md
> +Podman has a fantastic integration with `systemd`. I believe at this point the users are even able to run `systemd` **within** a container which makes perfect sense. Why would we have to use anything
```suggestion
Podman has fantastic integration with `systemd`. Users are even able to run `systemd` **within** a container which makes perfect sense. Why would we have to use anything different inside a container than we already got used to outside of a container? Anyhow, we are not covering this, but managing containers with `systemd`. 
```

2021-04-09 08:36 UTC, thunderbirdtr commented on project/docs/install_podman.md
> +The `pod` concept has been introduced in Kuberentes and Docker users usually don't even think of the possibility or benefits to run pods in a local runtime or a development environment. Pods are grea
```suggestion
The `pod` concept has been introduced in Kubernetes and Docker users usually don't even think of the possibility or benefits to run pods in a local runtime or a development environment. Pods are great if, for example, you need a database (DB) container that you don't want to bind to a routable network. In comes the idea of the `pod`. Instead of binding the DB to a routable network, you can bind it to `localhost` therefore other containers within the pod can connect to it using `localhost` as they share the network namespace. Another use case can be to group containers in pods.
```

2021-04-09 08:36 UTC, thunderbirdtr commented on project/docs/install_podman.md
> +Every pod has an 'infra' container that functions as the namespace holder, stores data on port bindings, cgroup-parent values, and kernel namespaces are all assigned to the “infra” container. Once th
```suggestion
 Every pod has an 'infra' container that functions as the namespace holder, stores data on port bindings, cgroup-parent values, and kernel namespaces are all assigned to the “infra” container. Once the pod is created these values can not be changed. The pod can also allow starting, stop, pause multiple containers at once just by doing the same as would with a single container, but instead by container the commands can be executed by pods resulting in the desired effect, but faster and a lot more comfortably.
```

2021-04-09 08:36 UTC, thunderbirdtr commented on project/docs/install_podman.md
> +As Podman is daemonless, running containers doesn't require running them with root, but can be started with a user as well. Granted, rootless containers will have no access to networking and can't us
```suggestion
As Podman is daemonless, running containers doesn't require running them with root but can be started with a user as well. Granted, rootless containers will have no access to networking and can't use privileged ports, but it is a great way to keep the system secure. For instance, if an application escapes the container ran as a user it will be able to cause less damage and would have limited access to the system than if it would run as root. Rootfull containers are recommended for running applications that require access over privileged ports like a public facing `Nginx reverse proxy. Even in that case, there could be some rules implemented in the firewall that forwards requests, but that's a different story
```

2021-04-09 08:36 UTC, thunderbirdtr commented on project/docs/install_podman.md
> +Podman is a a daemonless, open-source tool to manage, deploy and build application containers. Podman is using Open Containers Initiative (OCI) Containers and container images, which means that conta
```suggestion
Podman is a daemon-less, open-source tool to manage, deploy and build application containers. Podman is using Open Containers Initiative (OCI) Containers and Container Images, which means that containers crated with/for Docker or CRI-o will work with Podman as well and vice versa. It is coming with a command-line interface (CLI) which offers pretty much the same commands as Docker does. How similar are Podman commands to Docker? Let's put it this way: many Podman users just alias `docker` to `podman`. Like other runtimes, Podman also relies on an OCI compliant container runtime to interface with the operating system. Podamn also has a RESTful API to manage containers, offers automatic updates of containers, and has a fantastic `systemd` integration.
```

2021-04-09 20:05 UTC, apinter commented
@thunderbirdtr can you please also ok the doc from a technical point of view just to make sure that everything written in it is correct and works?

2021-04-11 19:44 UTC, why-not-try-calmer requested changes
I think we don't want to remove project/mkdocs.yml. Also need to (re?) add podman to mkdocs.yml

2021-04-13 17:39 UTC, apinter commented
> I think we don't want to remove project/mkdocs.yml. Also need to (re?) add podman to mkdocs.yml

The lesson learned here: don't bar and commit. Apologies.

2021-04-13 21:06 UTC, merged