Proprietary gpu 2
openSUSE/openSUSE-docs-revamped pull request #51
Opened 2021-01-17 03:52 UTC by camckay

2021-01-17 18:39 UTC, daviddyess requested changes

2021-01-17 18:39 UTC, daviddyess commented on project/docs/install_proprietary.md
>  3. On the menu, click __Configuration__ > __Repositories__... (or do `Ctrl + R`).
Please use `&gt;` instead of `>`

2021-01-17 19:44 UTC, camckay commented on project/docs/install_proprietary.md
>  3. On the menu, click __Configuration__ > __Repositories__... (or do `Ctrl + R`).
Done.

2021-01-18 08:54 UTC, Nycticorax requested changes
Thanks for this PR, great addition to the page! Just a quick comment:

"Recent AMD APUs and Nvidia" is just like "OFFLOADING SPECIFIC APPLICATIONS TO THE NVIDIA GPU" except for the line reading "The open source AMD GPU drivers will load by default.". So I wonder if "Recent AMD APUs..." requires a separate sections of its own. If the point you are making is that setting up drivers for new APUs is very similar to what you've described already, what about removing the section and adding instead a note or info box like
```
??? info "Recent AMD APUs and Nvidia"
    The above instructions work the same (your words here).
```
? Similar examples can be found under `desktop_choice.md`.

2021-01-18 14:29 UTC, camckay commented
> f the point you are making is that setting up drivers for new APUs is very similar to what you've described already

I see your point. My thoughts in creating a separate section were twofold...

1. If someone is scanning the page looking for their particular hardware combination, the information needed would mostly be in that section.
2. This is a relatively new combination in laptops. So I only have a sample size of 1 - I have a single laptop with this configuration. So I wasn't sure if my experience would hold, or if others might have something to add to this section.

2021-01-19 13:01 UTC, Nycticorax commented
> > f the point you are making is that setting up drivers for new APUs is very similar to what you've described already
> 
> I see your point. My thoughts in creating a separate section were twofold...
> 
> 1. If someone is scanning the page looking for their particular hardware combination, the information needed would mostly be in that section.
> 2. This is a relatively new combination in laptops. So I only have a sample size of 1 - I have a single laptop with this configuration. So I wasn't sure if my experience would hold, or if others might have something to add to this section.

Okay, let's go that road then. A few quirks:

- If we follow the logic your suggesting, we should fix the names in the entire document. Can you do it? "Nvidia driver" => "GPU drivers" or something along these lines.
- If we follow this logic we should also change the structure. Can you do it? I have in mind somethng like i.e.
  - Nvidia dedicated + Intel integrated
  - Nvidia dedicated
  - AMD dedicated & integrated (is the same as AMD APUs?)
  - AMD dedicated
- "Recent AMD APUs and Nvidia" had a redundant numbering. Fixed it myself.

2021-01-19 13:10 UTC, Nycticorax commented
> > f the point you are making is that setting up drivers for new APUs is very similar to what you've described already
> 
> I see your point. My thoughts in creating a separate section were twofold...
> 
> 1. If someone is scanning the page looking for their particular hardware combination, the information needed would mostly be in that section.
> 2. This is a relatively new combination in laptops. So I only have a sample size of 1 - I have a single laptop with this configuration. So I wasn't sure if my experience would hold, or if others might have something to add to this section.

Okay, so let's follow this logic to the end: can you restructure -- and rename when required -- the sections to cover these use cases? One reasonable structure seems to go like:
  - Intel integrated + Nvidia dedicated
  - Nvidia dedicated
  - Intel integrated + AMD dedicated
  - AMD dedicated
 I don't know where AMD APUs would fit in this structure, but I am sure you'll find a sweet spot :)

2021-01-26 08:36 UTC, Nycticorax commented
@camckay still around?

2021-01-28 17:06 UTC, vegetable-broth commented
I notice we should use https://github.com/openSUSE/SUSEPrime and say more on how to power off the NVidia GPU when not in use.

2021-01-28 17:42 UTC, camckay commented
I agree. Should I split that section out then and push it to a new section?

On Jan 28, 2021 11:06 AM, Ad <notifications@github.com> wrote:

I notice we should use https://github.com/openSUSE/SUSEPrime<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FopenSUSE%2FSUSEPrime&data=04%7C01%7C%7C1c55a16bc4cc433084c808d8c3af079d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474503797981927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7CjjLBrYmoxBWQfAmb9K7hFB0wdbMMXNemD2aCn3%2F5k%3D&reserved=0> and say more on how to power off the NVidia GPU when not in use.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FopenSUSE%2FopenSUSE-docs-revamped%2Fpull%2F51%23issuecomment-769230777&data=04%7C01%7C%7C1c55a16bc4cc433084c808d8c3af079d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474503797991934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EusnL8yBAzO6JIo5Ey%2FVeDSkjW4V%2BDLJXIjhJJIi0oc%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIM34V57SI4CUEAZNYQJIHTS4GKQVANCNFSM4WFY27FA&data=04%7C01%7C%7C1c55a16bc4cc433084c808d8c3af079d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637474503798001921%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=px5KCp7xeKFCUeiO%2BLMuap51YUxLm7lJYk7nGD2dV6s%3D&reserved=0>.

2021-01-28 17:45 UTC, vegetable-broth commented
> I agree. Should I split that section out then and push it to a new section?

Would be great!

2021-02-04 02:39 UTC, camckay commented
Okay, I think the way I have it set up now looks quite a bit better. I got separate doc created for the hybrid graphic config, and tried to add some more clarity to that section, with a clearer distinction between onboard AMD and Intel graphics. But I combined the section on offloading, since it is the same regardless of which onboard gpu you use.

2021-02-04 08:35 UTC, why-not-try-calmer approved these changes
very cool, it's indeed better! let's continue this conversation in the Issues.

2021-02-04 08:36 UTC, merged